### ISSUE TITLE
TypeError: homebridgeAccessory.getService is not a function

### ISSUE THREAD

**Issue by tillsteinbach** [SynTexDZN/homebridge-syntex-knx#10]
**Describe the bug**
The plugin keeps restarting with following log:

```
[SynTexKNX] [DEBUG] KNX IP Gateway disconnected!

/homebridge/node_modules/homebridge-syntex-knx/node_modules/homebridge-syntex-dynamic-platform/src/info.js:10
                var service = homebridgeAccessory.getService(Service.AccessoryInformation);
                                    ^
[SynTexKNX] [ERROR] TypeError: homebridgeAccessory.getService is not a function
    at new AccessoryInformationService (/homebridge/node_modules/homebridge-syntex-knx/node_modules/homebridge-syntex-dynamic-platform/src/info.js:10:37)
    at SynTexUniversalAccessory.setAccessoryInformation (/homebridge/node_modules/homebridge-syntex-knx/node_modules/homebridge-syntex-dynamic-platform/src/universal.js:112:17)
    at new UniversalAccessory (/homebridge/node_modules/homebridge-syntex-knx/node_modules/homebridge-syntex-dynamic-platform/src/universal.js:53:8)
    at new SynTexUniversalAccessory (/homebridge/node_modules/homebridge-syntex-knx/src/universal.js:24:3)
    at SynTexKNXPlatform.loadAccessories (/homebridge/node_modules/homebridge-syntex-knx/index.js:44:22)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-syntex-knx/index.js:27:10)
    at HomebridgeAPI.emit (node:events:527:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:189:14)

( [info.js] at line [10] )
[12/23/2022, 9:49:55 AM] [SynTexKNX] Child bridge process ended
[12/23/2022, 9:49:55 AM] [SynTexKNX] Process Ended. Code: 1, Signal: null
[12/23/2022, 9:50:02 AM] [SynTexKNX] Restarting Process...
[12/23/2022, 9:50:03 AM] [SynTexKNX] Launched child bridge with PID 13857
```

**Expected behavior**
No restarts

**Config**
```
{
    "platform": "SynTexKNX",
    "name": "SynTexKNX",
    "ip": "10.11.2.200",
    "accessories": [
        {
            "id": "KNX_System_LED-Sperrobjekt",
            "name": "Taster LEDs",
            "services": [
                {
                    "datapoint": "1.003",
                    "address": {
                        "status": "9/0/8",
                        "control": "9/0/8"
                    },
                    "type": "switch",
                    "inverted": true,
                    "name": "Taster LEDs"
                }
            ]
        },
        {
            "id": "KNX_DG-Flur-Praesenz-Temperatur",
            "name": "Temperatur Sensor Flur Decke",
            "services": [
                {
                    "address": {
                        "status": "7/3/3"
                    },
                    "type": "temperature",
                    "name": "DG Flur Temperatur"
                },
                {
                    "address": {
                        "status": "7/5/0"
                    },
                    "type": "light",
                    "name": "DG Flur Helligkeit"
                }
            ]
        },
        {
            "id": "KNX_DG-Flur-Praesenz-Temperatur",
            "name": "Temperatur Sensor Flur Decke",
            "services": [
                {
                    "address": {
                        "status": "7/3/3"
                    },
                    "type": "temperature",
                    "name": "DG Flur Temperatur"
                },
                {
                    "address": {
                        "status": "7/5/0"
                    },
                    "type": "light",
                    "name": "DG Flur Helligkeit"
                }
            ]
        },
        {
            "id": "KNX_DG-Flur-Treppe-Taster",
            "name": "Taster Flur Treppe",
            "services": [
                {
                    "address": {
                        "status": "7/3/5"
                    },
                    "type": "temperature",
                    "name": "DG Flur Treppe Temperatur"
                }
            ]
        },
        {
            "id": "KNX_EG-Diele-Taster",
            "name": "Taster Diele",
            "services": [
                {
                    "address": {
                        "status": "7/3/1"
                    },
                    "type": "temperature",
                    "name": "EG Diele Temperatur"
                },
                {
                    "address": {
                        "status": "7/4/0"
                    },
                    "type": "humidity",
                    "name": "EG Diele Luftfeuchte"
                }
            ]
        },
        {
            "id": "KNX_EG-Speisekammer-Taster",
            "name": "Taster Speisekammer",
            "services": [
                {
                    "address": {
                        "status": "7/3/4"
                    },
                    "type": "temperature",
                    "name": "EG Speisekammer Temperatur"
                },
                {
                    "address": {
                        "status": "7/5/1"
                    },
                    "type": "light",
                    "name": "EG Speisekammer Helligkeit"
                }
            ]
        },
        {
            "id": "KNX_DG-Flur-Lichtleiste",
            "name": "DG Flur Lichtleiste",
            "services": [
                {
                    "address": {
                        "status": "0/4/1",
                        "control": "0/1/1"
                    },
                    "type": "led",
                    "name": "DG Flur Lichtleiste"
                }
            ]
        },
        {
            "id": "KNX_EG-Speisekammer-Licht",
            "name": "EG Speisekammer Licht",
            "services": [
                {
                    "address": {
                        "status": "0/4/2",
                        "control": "0/1/2"
                    },
                    "type": "led",
                    "name": "EG Speisekammer Licht"
                }
            ]
        }
    ],
    "_bridge": {
        "username": "0E:39:BB:A1:AE:E1",
        "port": 30083
    }
}
```

**Comment by tillsteinbach** [comment]
I just downgraded to 1.0.0 and the error is gone. So this is probably introduced with 1.0.1

**Comment by SynTexDZN** [comment]
Hey @tillsteinbach,
Es sieht danach aus, dass einige von deinen Geräten einen fehlerhaften Cache haben. Bitte führe zunächst ein Update auf die neuste Version durch. Danach musst du eine Datei mit dem Pfad `/accessories/cachedAccessories` finden, in der die Homebridge ihre Daten speichert. Du kannst nun entweder selektiv alle SynTexKNX Geräte entfernen oder gleich die gesamte Datei.

### Achtung
Durch Löschen der ganzen Datei werden auch alle Homebridge-Geräte in HomeKit neu eingespielt. Das bedeutet, dass z.B. die Zuordnung zu Räumen oder Geräte-Symbole verloren gehen.

~ **SynTex**

**Comment by tillsteinbach** [comment]
Hmm, mist. Habe bestimmt 50 devices. Man kann nicht rausfinden welches Gerät den fehlerhaften Cache hat?

**Comment by SynTexDZN** [comment]
Theoretisch schon. Dazu müsstest du meinen Code etwas abändern.
1. Suche zunächst nach der Datei `/homebridge/node_modules/homebridge-syntex-knx/node_modules/homebridge-syntex-dynamic-platform/src/info.js`
2. Füge unter der Zeile 8 den Code `console.log(deviceConfig, serviceConfig)` ein
3. Nun müsstest du vor dem Fehler die Geräte Config angezeigt bekommen
