### ISSUE TITLE
ipaddr: the address has neither IPv6 nor IPv4 format

### ISSUE THREAD

**Issue by curana** [SynTexDZN/homebridge-syntex-knx#11]
**Describe the bug**
I installed and configured SyntexKNX in Homebridge which is running in a Docker Container.

At startup it says:
`[SynTexKNX] [ERROR] Error: ipaddr: the address has neither IPv6 nor IPv4 format`

**Expected behavior**
I expect either the right IP address to be identified or a parameter in the config available to specify which IP address to bind to.

**Config**
`{
    "baseDirectory": "/homebridge/SynTex/KNX",
    "debug": false,
    "platform": "SynTexKNX",
    "ip": "<my_knx-gateway_hostname>",
    "accessories": [
        {
            "id": "my_light",
            "name": "Light",
            "services": [
                {
                    "address": {
                        "status": [
                            "1/0/30"
                        ],
                        "control": [
                            "1/1/30"
                        ]
                    },
                    "type": "switch"
                }
            ]
        }
    ],
    "language": "de"
}`

**Logs**
`[SynTexKNX] [ERROR] Error: ipaddr: the address has neither IPv6 nor IPv4 format
    at Object.ipaddr.parse (/homebridge/node_modules/homebridge-syntex-knx/node_modules/ipaddr.js/lib/ipaddr.js:493:13)
    at fsm.initialize (/homebridge/node_modules/homebridge-syntex-knx/node_modules/knx/src/FSM.js:30:20)
    at fsm.BehavioralFsm (/homebridge/node_modules/homebridge-syntex-knx/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:12:1)
    at fsm.constructor (/homebridge/node_modules/homebridge-syntex-knx/node_modules/machina/lib/webpack:/src/Fsm.js:7:1)
    at new fsm (/homebridge/node_modules/homebridge-syntex-knx/node_modules/machina/lib/webpack:/src/utils.js:135:1)
    at Object.Connection (/homebridge/node_modules/homebridge-syntex-knx/node_modules/knx/src/Connection.js:354:16)
    at new KNXInterface (/homebridge/node_modules/homebridge-syntex-knx/src/device-manager.js:18:25)
    at new DeviceManager (/homebridge/node_modules/homebridge-syntex-knx/src/device-manager.js:258:23)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-syntex-knx/index.js:25:21)
    at HomebridgeAPI.emit (node:events:525:35)

( [ipaddr.js] at line [493] )
[SynTexKNX] [ERROR] [SynTexKNX.txt] could not be read!
[Error: ENOENT: no such file or directory, open '/homebridge/SynTex/KNX/activity/SynTexKNX.txt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/homebridge/SynTex/KNX/activity/SynTexKNX.txt'
}
[SynTexKNX] [ERROR] [SynTexKNX.txt] could not be read!
[Error: ENOENT: no such file or directory, open '/homebridge/SynTex/KNX/activity/SynTexKNX.txt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/homebridge/SynTex/KNX/activity/SynTexKNX.txt'
}
[SynTexKNX] [ERROR] [automation.json] could not be read!
[Error: ENOENT: no such file or directory, open '/homebridge/SynTex/KNX/automation/automation.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/homebridge/SynTex/KNX/automation/automation.json'
}`

**Screenshots**
n/a

**More Information**
 - Homebridge 1.6.0
 - node.js: 18.12.1

**Comment by SynTexDZN** [comment]
Hey @curana, thanks for your report.
Your issue belongs to the "optional" port parameter, which isn't defined in your config. Normally it should be optional but in your case the fastest way to solve this issue is to add it anyways. https://github.com/SynTexDZN/homebridge-syntex-knx#optional-parameters

**Comment by SynTexDZN** [comment]
Hey @curana, thanks for your report.
It looks like there is a problem with the format of your gateway ip address. Without that information it's difficult to say what is wrong there.

~ **SynTex**

**Comment by curana** [comment]
You are right, I provided my KNX Hostname here.
I fixed it but now I'm getting another error.

I will create a new issue to not mix it up here.

Thanks for your help!
