### ISSUE TITLE
Debug messages are printed and error on startup.

### ISSUE THREAD

**Issue by curana** [SynTexDZN/homebridge-syntex-knx#12]
**Describe the bug**
I get an error when starting Homebride with SynTexKNX enabled and also all debug messages are being printed.
Seems the debug: "false" parameter doesn't work or I misunderstood the example.

**Expected behavior**
No debug messages and no error.

**Config**
`{ "baseDirectory": "/homebridge/SynTex/KNX", "debug": false, "platform": "SynTexKNX", "ip": "<my_knx-gateway_hostname>", "accessories": [ { "id": "my_light", "name": "Light", "services": [ { "address": { "status": [ "1/0/30" ], "control": [ "1/1/30" ] }, "type": "switch" } ] } ], "language": "de" }`

**Logs**
`[SynTexKNX] [ERROR] Error: Request failed with status code 404 ( [createError.js] at line [16] )
    at createError (/homebridge/node_modules/homebridge-syntex-knx/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-syntex-knx/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-syntex-knx/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Screenshots**
n/a

**More Information**
 - OS: Ubuntu Focal Fossa (Docker)
 - NodeJS: 18.12.1

**Additional context**

**Comment by SynTexDZN** [comment]
Hey @curana,
That debug logs are still printed is because you have to add the `debug` parameter to the `log` object like in the [Example Config](https://github.com/SynTexDZN/homebridge-syntex-knx/blob/main/config-sample.json).
The error you see is known and solved with the latest beta of my plugin but you can also ignore it because it's not a critical issue.

~ **SynTex**

**Comment by curana** [comment]
Ok, thanks, I fixed it and will wait for the next version.
Thanks!
